### ISSUE TITLE
Design comments

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel-app#27]
- [ ] The red of the play icon is not the same as the red of the background.  (Referenced in #24 )
- [ ] We should include an instructional screen somewhere after the 3 options, that tells you to swipe to advance. It’s not obvious because at that point you’ve clicked to advance. (Moved to #28 )
## Play
- [x] Red arrow icon is really lo-res 
- [ ] The top navigation with the arrow to the right implies to me that you can go to the previous screen, not to the beginning of the game (therefore losing all your game progress). If we want it to advance to the start, maybe it should be a little home icon instead. (Referenced in #24 )
- [x] The way the comparison is set up could be clearer. I’d suggest making text grey, rather than blue, making the word ‘and’ red and lowercase (so it doesn’t read like part of the name or title).
  _This needs some extra markup in question.json which I will go through_
- [x] Click area for answers should extend to the radio button as well, since I keep wanting to click there, then have to click on the answer instead
## Connect
- [x] I can seem to scroll the main screen with curators down without selecting one. How can we fix that. Maybe only the name is a click area?
- [x] Can we include an outline around each circle with the portrait image. The portraits on white (unless we added a background, don’t look so great.
  ![screen shot 2015-05-17 at 12 16 25 pm](https://cloud.githubusercontent.com/assets/1565953/8107350/81540f34-1040-11e5-8386-63286cf54609.png)
- [x] When you swipe after reading a curator’s bio, the next screen is at the bottom so you have to scroll up to see the artwork. Can we fix that so that with each swipe you are at the top of the screen

**Comment by robertocarroll** [comment]
Closing this issue - shifted remaining incomplete ones to other issues.
