### ISSUE TITLE
Refinements

### ISSUE THREAD

**Issue by clintmclean** [robertocarroll/barjeel-app#32]
App tweaks and refinements:
- [ ] Barjeel logo on load screen is squished
- Need loading image between Play and first question (very slow to advance from Play instruction page.
  Moved to #34 
- Change Connect layout to the single column layout as used formerly by Discover.
  Moved to #33 

From the call last night: 
- [x] Match up red with red in icons. UJ to send hex. // _The red in the double arrow seems to be #EE4023 and the $barjeel-red I have is #FF3300. I'm going to change the barjeel-red to #EE4023._ See https://github.com/robertocarroll/barjeel-app/commit/62a3c0c830a2fa70adcdcd5b58ca1e8c124138b5 
- [x] Transition - needs to be other way from initial screen. (RC) // _I think I've fixed this, but please confirm_
- [x] Remove splash screens (RC). See https://github.com/robertocarroll/barjeel-app/commit/f390572c8b594d941b81ca2023b20019d929f292
- [x] UJ to provide new home layout. 
- [x] Play text - edit.
- [x] Home icon - to replace back arrow on play and connect (except single layout in connect). UJ to provide. 
- [x] Note about accidentally tapping the first choice when scrolling. Consider making dots bigger and making them the only hit area, but concluded to leave for now. 
- [x] Increase space between choice to 1.5 time current on play questions (RC). see https://github.com/robertocarroll/barjeel-app/commit/c9d9c8a847e813631fd009d1004e53b8125dc3b6
- [x] Reduce space between top bar and "What's the connection?" Match the space up with the wrong and right answer screens, so they all match (RC). see https://github.com/robertocarroll/barjeel-app/commit/c9d9c8a847e813631fd009d1004e53b8125dc3b6
- [x] Same space above and below <-> double arrow. Tweak z-index so it always sits on top of everything else. (RC) see https://github.com/robertocarroll/barjeel-app/commit/c9d9c8a847e813631fd009d1004e53b8125dc3b6
- [x] Make arrow heavier - to match the empty hearts thickness. (CM?)
- [x] Heart arrows need high quality versions for different lives (see #24) (CM?)
- [x] How do people know to tap the round images to see full image? UJ to provide an icon which will go on each image in a corner (round image so it will always be on white background). (adding to #24)
- [x] Score - make correct score / number of questions completed (RC) // _Perhaps needs design_
- [ ] Date and dimensions in connect images. CM to standardise.  
- [ ] Missing images and double-check filenames and images match (CM) // Moved to #37

**Comment by robertocarroll** [comment]
I'm going to break this out into a couple of separate issues if that's OK.

**Comment by clintmclean** [comment]
Yep no problem - thought you may prefer individual issues.

**Comment by robertocarroll** [comment]
The Barjeel logo being squished is all about the splash screens and the different dimensions of different phones. It's fine on my iPhone 4. Which device are you using? 

The dimensions are defined here: https://github.com/robertocarroll/barjeel-app/blob/gh-pages/config.xml

And we discussed the splash screens in #24 I can't remember if we did them all, but I think I've seen a tool to create them all automatically which I will try to find and post here.

**Comment by robertocarroll** [comment]
From the call last night: 

- [ ] Match up red with red in icons. UJ to send hex.
- [ ] Transition - needs to be other way from initial screen. (RC)
- [ ] Remove splash screens (RC). UJ to provide new home layout. 
- [ ] Play text - edit.
- [ ] Home icon - to replace back arrow on play and connect (except single layout in connect). UJ to provide. 
- [x] Note about accidentally tapping the first choice when scrolling. Consider making dots bigger and making them the only hit area, but concluded to leave for now. 
- [ ] Increase space between choice to 1.5 time current on play questions (RC). 
- [ ] Reduce space between top bar and "What's the connection?" Match the space up with the wrong and right answer screens, so they all match (RC).
- [ ] Same space above and below <-> double arrow. Tweak z-index so it always sits on top of everything else. (RC) 
- [ ] Make arrow heavier - to match the empty hearts thickness. (CM?)
- [ ] Heart arrows need high quality versions for different lives (see #24) (CM?)
- [ ] How do people know to tap the round images to see full image? UJ to provide an icon which will go on each image in a corner (round image so it will always be on white background). (adding to #24)
- [ ] Score - make correct score / number of questions completed (RC)
- [ ] Date and dimensions in connect images. CM to standardise.

**Comment by robertocarroll** [comment]
Closing this issue and moving the remaining content things to a separate issue.
